
/* Generated by ai2jsx v0.89.0 - 2020-12-15 11:42 */
/* ai file: Panel1.ai */

import React from 'react';
import { styles } from './styles.scss';
import panel from './Panel1-Desktop.jpg';

const Desktop = () => (
  <div className={`Desktop ${styles}`}>
    <div id='g-Desktop-box'>
      <div id='g-Panel1-Desktop' className='g-artboard' style={ { "width": "800px", "height": "5693px"} } data-aspect-ratio='0.141' data-min-width='800'>
        <img id='g-Panel1-Desktop-img' className='g-aiImg g-aiAbs' alt='' src={panel} />
        <div id='g-ai0-1' className='g-Layer_1 g-aiAbs' style={ { "top": "0.6324%", "left": "14.8022%", "width": "33.125%"} }>
          <p>Lachlan, with the PEDs</p>
          <p>Tell, us, do you use them, please?</p>
        </div>
        <div id='g-ai0-2' className='g-Layer_1 g-aiAbs' style={ { "top": "5.3575%", "left": "53.1521%", "width": "32.375%"} }>
          <p>I would not snort them up my nose</p>
          <p>I would not drink them with a hose</p>
        </div>
        <div id='g-ai0-3' className='g-Layer_1 g-aiAbs' style={ { "top": "7.5356%", "left": "4.7894%", "width": "57.125%"} }>
          <p>I won't inject them in my ass</p>
          <p>I'll never, ever take the gas</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai0-4' className='g-Layer_1 g-aiAbs' style={ { "top": "16.0899%", "left": "14.214%", "width": "33%"} }>
          <p>Would you use them in the gi?</p>
          <p>Would you at ADCC?</p>
        </div>
        <div id='g-ai0-5' className='g-Layer_1 g-aiAbs' style={ { "top": "21.0083%", "left": "52.7912%", "width": "33%"} }>
          <p className='g-pstyle0'>I would not, could not, in the gi</p>
          <p className='g-pstyle0'>I would not at ADCC</p>
        </div>
        <div id='g-ai0-6' className='g-Layer_1 g-aiAbs' style={ { "top": "22.8878%", "left": "5.7799%", "width": "17.875%"} }>
          <p>I would not ever take the juice</p>
        </div>
        <div id='g-ai0-7' className='g-Layer_1 g-aiAbs' style={ { "top": "23.5025%", "left": "71.2715%", "width": "24.75%"} }>
          <p>I do not use those PEDs</p>
        </div>
        <div id='g-ai0-8' className='g-Layer_1 g-aiAbs' style={ { "top": "24.6267%", "left": "4.3058%", "width": "18.875%"} }>
          <p>I would not in the absolutes</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai0-9' className='g-Layer_1 g-aiAbs' style={ { "top": "25.2064%", "left": "76.5579%", "width": "18.25%"} }>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai0-10' className='g-Layer_1 g-aiAbs' style={ { "top": "32.2677%", "left": "14.8575%", "width": "30.625%"} }>
          <p>Lachlan, sorry for the spam</p>
          <p>But check out Gordon's Instagram!</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai0-11' className='g-Layer_1 g-aiAbs' style={ { "top": "36.9401%", "left": "53.0496%", "width": "33.25%"} }>
          <p>Right now I'm fully at a loss</p>
          <p>Did he just say I'm on the sauce?</p>
        </div>
        <div id='g-ai0-12' className='g-Layer_1 g-aiAbs' style={ { "top": "39.2763%", "left": "5.4705%", "width": "50.5%"} }>
          <p>Why did he post that? Is he high?</p>
          <p>I can't believe this fucking guy</p>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
          <p>I would not ever take the juice</p>
          <p>I would not in the absolutes</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai0-13' className='g-Layer_1 g-aiAbs' style={ { "top": "48.3752%", "left": "4.8572%", "width": "56.375%"} }>
          <p>Did you use in your last fight?</p>
          <p>Tell us, please, was Gordon right?</p>
        </div>
        <div id='g-ai0-14' className='g-Layer_1 g-aiAbs' style={ { "top": "50.1317%", "left": "27.4361%", "width": "51.25%"} }>
          <p>I did not use in my last fight</p>
          <p>I tell you Gordon was not right</p>
          <p>I am natty, don't you see?</p>
          <p>The scientists can test my pee</p>
        </div>
        <div id='g-ai0-15' className='g-Layer_1 g-aiAbs' style={ { "top": "52.6085%", "left": "45.8863%", "width": "43.25%"} }>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
        </div>
        <div id='g-ai0-16' className='g-Layer_1 g-aiAbs' style={ { "top": "54.4353%", "left": "57.765%", "width": "36.5%"} }>
          <p>I would not ever take the juice</p>
          <p>I would not in the </p>
          <p>absolutes</p>
          <p>&nbsp;</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai0-17' className='g-Layer_1 g-aiAbs' style={ { "top": "60.0386%", "left": "50.7927%", "marginLeft": "-26.9375%", "width": "53.875%"} }>
          <p className='g-pstyle1'>Lachlan, Lachlan, don't be cross</p>
          <p className='g-pstyle1'>But everyone is on the sauce.</p>
        </div>
        <div id='g-ai0-18' className='g-Layer_1 g-aiAbs' style={ { "top": "65.4137%", "left": "4.9085%", "width": "51.25%"} }>
          <p>I've competed with the best</p>
          <p>And trust me, some would pass a test</p>
          <p>I don't want this to be a sport</p>
          <p>Where clean guys always come up short</p>
          <p>So let's not tell those who compete</p>
          <p>That those who win must always cheat</p>
        </div>
        <div id='g-ai0-19' className='g-Layer_1 g-aiAbs' style={ { "top": "73.4586%", "left": "45.9132%", "width": "52.25%"} }>
          <p>We should not use those PEDs</p>
          <p>We should not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai0-20' className='g-Layer_1 g-aiAbs' style={ { "top": "74.8639%", "left": "14.7425%", "width": "32.25%"} }>
          <p>Lachlan, please now, don't be mad</p>
          <p>But tell us, are those drugs so bad?</p>
        </div>
        <div id='g-ai0-21' className='g-Layer_1 g-aiAbs' style={ { "top": "79.7646%", "left": "53.1838%", "width": "33.25%"} }>
          <p>The side effects I cannot list</p>
          <p>I'm no endocrinologist</p>
        </div>
        <div id='g-ai0-22' className='g-Layer_1 g-aiAbs' style={ { "top": "81.6793%", "left": "5.4071%", "width": "58.375%"} }>
          <p>But we all know they're bad for you</p>
          <p>I will not die at fifty-two</p>
          <p>I would not, could not, take the gas</p>
        </div>
        <div id='g-ai0-23' className='g-Layer_1 g-aiAbs' style={ { "top": "83.629%", "left": "52.5576%", "width": "42.875%"} }>
          <p>I do not need that muscle mass</p>
          <p>They may be big while I am small</p>
          <p>But I don't need turinabol</p>
        </div>
        <div id='g-ai0-24' className='g-Layer_1 g-aiAbs' style={ { "top": "90.6025%", "left": "5.3527%", "width": "55.25%"} }>
          <p>Regardless of their body frame</p>
          <p>I'll tear their ACLs the same</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai0-25' className='g-Layer_1 g-aiAbs' style={ { "top": "92.7455%", "left": "81.7036%", "marginLeft": "-13.6875%", "width": "27.375%"} }>
          <p className='g-pstyle1'>Good luck at Abu Dhabi trials!</p>
          <p className='g-pstyle1'>Thank you, thank you, Lachlan Giles!</p>
        </div>
        <div id='g-ai0-26' className='g-Layer_1 g-aiAbs' style={ { "top": "92.763%", "left": "18.5294%", "marginLeft": "-13.625%", "width": "27.25%"} }>
          <p className='g-pstyle1'>You've convinced us, now we see</p>
          <p className='g-pstyle1'>We'll never use those PEDs!</p>
        </div>
      </div>
    </div>
  </div>
);

export default Desktop;
/* End ai2jsx - 2020-12-15 11:42 */
