
/* Generated by ai2jsx v0.89.0 - 2020-12-15 13:51 */
/* ai file: Panel1.ai */

import React from 'react';
import { styles } from './styles.scss';
import panel from './Panel1-XSMobile.jpg';

const XSMobile = () => (
  <div className={`XSMobile ${styles}`}>
    <div id='g-XSMobile-box'>
      <div id='g-Panel1-XSMobile' className='g-artboard' style={ { "width": "290px", "height": "2087px"} } data-aspect-ratio='0.139' data-min-width='290' data-max-width='449'>
        <img id='g-Panel1-XSMobile-img' className='g-aiImg g-aiAbs' alt='' src={panel} />
        <div id='g-ai3-1' className='g-Layer_1 g-aiAbs' style={ { "top": "0.6708%", "left": "6.4252%", "width": "41.7241%"} }>
          <p>Lachlan, with the PEDs</p>
          <p>Tell, us, do you use them, please?</p>
        </div>
        <div id='g-ai3-2' className='g-Layer_1 g-aiAbs' style={ { "top": "6.1811%", "left": "54.6999%", "width": "41.7241%"} }>
          <p>I would not snort them up my nose</p>
          <p>I would not drink them with a hose</p>
        </div>
        <div id='g-ai3-3' className='g-Layer_1 g-aiAbs' style={ { "top": "8.7686%", "left": "7.3329%", "width": "54.8276%"} }>
          <p>I won't inject them in my ass</p>
          <p>I'll never, ever take the gas</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-4' className='g-Layer_1 g-aiAbs' style={ { "top": "16.6747%", "left": "5.7925%", "width": "41.7241%"} }>
          <p>Would you use them in the gi?</p>
          <p>Would you at ADCC?</p>
        </div>
        <div id='g-ai3-5' className='g-Layer_1 g-aiAbs' style={ { "top": "22.4724%", "left": "54.1878%", "width": "41.7241%"} }>
          <p className='g-pstyle0'>I would not, could not, in the gi</p>
          <p className='g-pstyle0'>I would not at ADCC</p>
        </div>
        <div id='g-ai3-6' className='g-Layer_1 g-aiAbs' style={ { "top": "24.6287%", "left": "6.2579%", "width": "23.1034%"} }>
          <p>I would not ever take the juice</p>
        </div>
        <div id='g-ai3-7' className='g-Layer_1 g-aiAbs' style={ { "top": "24.9641%", "left": "70.0754%", "width": "21.7241%"} }>
          <p>I do not use those PEDs</p>
        </div>
        <div id='g-ai3-8' className='g-Layer_1 g-aiAbs' style={ { "top": "26.2578%", "left": "6.4153%", "width": "18.6207%"} }>
          <p>I would not in the absolutes</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai3-9' className='g-Layer_1 g-aiAbs' style={ { "top": "26.4494%", "left": "79.4561%", "width": "16.8966%"} }>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-10' className='g-Layer_1 g-aiAbs' style={ { "top": "33.1576%", "left": "6.9736%", "width": "39.3103%"} }>
          <p>Lachlan, sorry for the spam</p>
          <p>But check out Gordon's Instagram!</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai3-11' className='g-Layer_1 g-aiAbs' style={ { "top": "38.5721%", "left": "54.2102%", "width": "41.0345%"} }>
          <p>Right now I'm fully at a loss</p>
          <p>Did he just say I'm on the sauce?</p>
        </div>
        <div id='g-ai3-12' className='g-Layer_1 g-aiAbs' style={ { "top": "41.1596%", "left": "6.9005%", "width": "54.4828%"} }>
          <p>Why did he post that? Is he high?</p>
          <p>I can't believe this fucking guy</p>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
          <p>I would not ever take the juice</p>
          <p>I would not in the absolutes</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-13' className='g-Layer_1 g-aiAbs' style={ { "top": "50.1677%", "left": "8.399%", "width": "57.931%"} }>
          <p>Did you use in your last fight?</p>
          <p>Tell us, please, was Gordon right?</p>
        </div>
        <div id='g-ai3-14' className='g-Layer_1 g-aiAbs' style={ { "top": "51.5093%", "left": "28.2617%", "width": "54.4828%"} }>
          <p>I did not use in my last fight</p>
          <p>I tell you Gordon was not right</p>
          <p>I am natty, don't you see?</p>
          <p>The scientists can test my pee</p>
        </div>
        <div id='g-ai3-15' className='g-Layer_1 g-aiAbs' style={ { "top": "54.3364%", "left": "40.5694%", "width": "54.4828%"} }>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
        </div>
        <div id='g-ai3-16' className='g-Layer_1 g-aiAbs' style={ { "top": "55.8697%", "left": "60.6294%", "width": "32.069%"} }>
          <p>I would not ever take the juice</p>
          <p>I would not in the </p>
          <p>absolutes</p>
        </div>
        <div id='g-ai3-17' className='g-Layer_1 g-aiAbs' style={ { "top": "58.3134%", "left": "60.9251%", "width": "35.1724%"} }>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-18' className='g-Layer_1 g-aiAbs' style={ { "top": "60.9487%", "left": "49.925%", "marginLeft": "-27.2414%", "width": "54.4828%"} }>
          <p className='g-pstyle1'>Lachlan, Lachlan, don't be cross</p>
          <p className='g-pstyle1'>But everyone is on the sauce.</p>
        </div>
        <div id='g-ai3-19' className='g-Layer_1 g-aiAbs' style={ { "top": "65.7403%", "left": "6.9297%", "width": "70.3448%"} }>
          <p>I've competed with the best</p>
          <p>And trust me, some would pass a test</p>
          <p>I don't want this to be a sport</p>
          <p>Where clean guys always come up short</p>
          <p>So let's not tell those who compete</p>
          <p>That those who win must always cheat</p>
        </div>
        <div id='g-ai3-20' className='g-Layer_1 g-aiAbs' style={ { "top": "73.0714%", "left": "29.1466%", "width": "68.6207%"} }>
          <p>We should not use those PEDs</p>
          <p>We should not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-21' className='g-Layer_1 g-aiAbs' style={ { "top": "74.6047%", "left": "6.9367%", "width": "40%"} }>
          <p>Lachlan, please now, don't be mad</p>
          <p>But tell us, are those drugs so bad?</p>
        </div>
        <div id='g-ai3-22' className='g-Layer_1 g-aiAbs' style={ { "top": "80.4025%", "left": "54.438%", "width": "41.0345%"} }>
          <p>The side effects I cannot list</p>
          <p>I'm no endocrinologist</p>
        </div>
        <div id='g-ai3-23' className='g-Layer_1 g-aiAbs' style={ { "top": "82.4149%", "left": "7.2615%", "width": "79.6552%"} }>
          <p>But we all know they're bad for you</p>
          <p>I will not die at fifty-two</p>
          <p>I would not, could not, take the gas</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai3-24' className='g-Layer_1 g-aiAbs' style={ { "top": "84.1878%", "left": "42.496%", "width": "53.7931%"} }>
          <p>I do not need that muscle mass</p>
          <p>They may be big while I am small</p>
          <p>But I don't need turinabol</p>
        </div>
        <div id='g-ai3-25' className='g-Layer_1 g-aiAbs' style={ { "top": "90.1773%", "left": "6.7241%", "width": "66.5517%"} }>
          <p>Regardless of their body frame</p>
          <p>I'll tear their ACLs the same</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-26' className='g-Layer_1 g-aiAbs' style={ { "top": "92.621%", "left": "22.3864%", "marginLeft": "-16.8966%", "width": "33.7931%"} }>
          <p className='g-pstyle1'>You've convinced us, now we see</p>
          <p className='g-pstyle1'>We'll never use those PEDs!</p>
        </div>
        <div id='g-ai3-27' className='g-Layer_1 g-aiAbs' style={ { "top": "92.621%", "left": "81.239%", "marginLeft": "-13.2759%", "width": "26.5517%"} }>
          <p className='g-pstyle1'>Good luck at Abu Dhabi trials!</p>
          <p className='g-pstyle1'>Thank you, thank you, Lachlan Giles!</p>
        </div>
      </div>
    </div>
  </div>
);

export default XSMobile;
/* End ai2jsx - 2020-12-15 13:51 */
