
/* Generated by ai2jsx v0.89.0 - 2020-12-15 14:19 */
/* ai file: Panel1.ai */

import React from 'react';
import { styles } from './styles.scss';
import panel from './Panel1-XSMobile.jpg';

const XSMobile = () => (
  <div className={`XSMobile ${styles}`}>
    <div id='g-XSMobile-box'>
      <div id='g-Panel1-XSMobile' className='g-artboard' style={ { "width": "300px", "height": "2159px"} } data-aspect-ratio='0.139' data-min-width='300' data-max-width='399'>
        <img id='g-Panel1-XSMobile-img' className='g-aiImg g-aiAbs' alt='' src={panel} />
        <div id='g-ai3-1' className='g-Layer_1 g-aiAbs' style={ { "top": "0.6948%", "left": "5.7081%", "width": "42%"} }>
          <p>Lachlan, with the PEDs</p>
          <p>Tell, us, do you use them, please?</p>
        </div>
        <div id='g-ai3-2' className='g-Layer_1 g-aiAbs' style={ { "top": "6.2529%", "left": "54.415%", "width": "42%"} }>
          <p>I would not snort them up my nose</p>
          <p>I would not drink them with a hose</p>
        </div>
        <div id='g-ai3-3' className='g-Layer_1 g-aiAbs' style={ { "top": "8.8467%", "left": "6.624%", "width": "55.3333%"} }>
          <p>I won't inject them in my ass</p>
          <p>I'll never, ever take the gas</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-4' className='g-Layer_1 g-aiAbs' style={ { "top": "16.8597%", "left": "5.0698%", "width": "42%"} }>
          <p>Would you use them in the gi?</p>
          <p>Would you at ADCC?</p>
        </div>
        <div id='g-ai3-5' className='g-Layer_1 g-aiAbs' style={ { "top": "22.6957%", "left": "53.8984%", "width": "42%"} }>
          <p className='g-pstyle0'>I would not, could not, in the gi</p>
          <p className='g-pstyle0'>I would not at ADCC</p>
        </div>
        <div id='g-ai3-6' className='g-Layer_1 g-aiAbs' style={ { "top": "24.9189%", "left": "5.5393%", "width": "23.3333%"} }>
          <p>I would not ever take the juice</p>
        </div>
        <div id='g-ai3-7' className='g-Layer_1 g-aiAbs' style={ { "top": "25.1969%", "left": "69.9283%", "width": "22%"} }>
          <p>I do not use those PEDs</p>
        </div>
        <div id='g-ai3-8' className='g-Layer_1 g-aiAbs' style={ { "top": "26.5401%", "left": "5.6982%", "width": "19%"} }>
          <p>I would not in the absolutes</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai3-9' className='g-Layer_1 g-aiAbs' style={ { "top": "26.7253%", "left": "79.3929%", "width": "17%"} }>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-10' className='g-Layer_1 g-aiAbs' style={ { "top": "33.4877%", "left": "6.2614%", "width": "39.6667%"} }>
          <p>Lachlan, sorry for the spam</p>
          <p>But check out Gordon's Instagram!</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai3-11' className='g-Layer_1 g-aiAbs' style={ { "top": "38.9532%", "left": "53.921%", "width": "41.3333%"} }>
          <p>Right now I'm fully at a loss</p>
          <p>Did he just say I'm on the sauce?</p>
        </div>
        <div id='g-ai3-12' className='g-Layer_1 g-aiAbs' style={ { "top": "41.547%", "left": "6.1877%", "width": "55%"} }>
          <p>Why did he post that? Is he high?</p>
          <p>I can't believe this fucking guy</p>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
          <p>I would not ever take the juice</p>
          <p>I would not in the absolutes</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-13' className='g-Layer_1 g-aiAbs' style={ { "top": "50.6716%", "left": "7.6996%", "width": "58.6667%"} }>
          <p>Did you use in your last fight?</p>
          <p>Tell us, please, was Gordon right?</p>
        </div>
        <div id='g-ai3-14' className='g-Layer_1 g-aiAbs' style={ { "top": "52.0148%", "left": "27.7401%", "width": "55%"} }>
          <p>I did not use in my last fight</p>
          <p>I tell you Gordon was not right</p>
          <p>I am natty, don't you see?</p>
          <p>The scientists can test my pee</p>
        </div>
        <div id='g-ai3-15' className='g-Layer_1 g-aiAbs' style={ { "top": "54.8402%", "left": "40.1581%", "width": "55%"} }>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
        </div>
        <div id='g-ai3-16' className='g-Layer_1 g-aiAbs' style={ { "top": "56.415%", "left": "60.3977%", "width": "32.3333%"} }>
          <p>I would not ever take the juice</p>
          <p>I would not in the </p>
          <p>absolutes</p>
        </div>
        <div id='g-ai3-17' className='g-Layer_1 g-aiAbs' style={ { "top": "58.8235%", "left": "60.696%", "width": "35.6667%"} }>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-18' className='g-Layer_1 g-aiAbs' style={ { "top": "61.5563%", "left": "49.6121%", "marginLeft": "-27.5%", "width": "55%"} }>
          <p className='g-pstyle1'>Lachlan, Lachlan, don't be cross</p>
          <p className='g-pstyle1'>But everyone is on the sauce.</p>
        </div>
        <div id='g-ai3-19' className='g-Layer_1 g-aiAbs' style={ { "top": "66.3733%", "left": "6.2171%", "width": "71%"} }>
          <p>I've competed with the best</p>
          <p>And trust me, some would pass a test</p>
          <p>I don't want this to be a sport</p>
          <p>Where clean guys always come up short</p>
          <p>So let's not tell those who compete</p>
          <p>That those who win must always cheat</p>
        </div>
        <div id='g-ai3-20' className='g-Layer_1 g-aiAbs' style={ { "top": "73.7378%", "left": "28.633%", "width": "69.3333%"} }>
          <p>We should not use those PEDs</p>
          <p>We should not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-21' className='g-Layer_1 g-aiAbs' style={ { "top": "75.3126%", "left": "6.2241%", "width": "40.3333%"} }>
          <p>Lachlan, please now, don't be mad</p>
          <p>But tell us, are those drugs so bad?</p>
        </div>
        <div id='g-ai3-22' className='g-Layer_1 g-aiAbs' style={ { "top": "81.1487%", "left": "54.1508%", "width": "41.3333%"} }>
          <p>The side effects I cannot list</p>
          <p>I'm no endocrinologist</p>
        </div>
        <div id='g-ai3-23' className='g-Layer_1 g-aiAbs' style={ { "top": "83.1867%", "left": "6.5519%", "width": "80.3333%"} }>
          <p>But we all know they're bad for you</p>
          <p>I will not die at fifty-two</p>
          <p>I would not, could not, take the gas</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai3-24' className='g-Layer_1 g-aiAbs' style={ { "top": "84.9931%", "left": "42.1019%", "width": "54.3333%"} }>
          <p>I do not need that muscle mass</p>
          <p>They may be big while I am small</p>
          <p>But I don't need turinabol</p>
        </div>
        <div id='g-ai3-25' className='g-Layer_1 g-aiAbs' style={ { "top": "91.0144%", "left": "6.0096%", "width": "67.3333%"} }>
          <p>Regardless of their body frame</p>
          <p>I'll tear their ACLs the same</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai3-26' className='g-Layer_1 g-aiAbs' style={ { "top": "93.4692%", "left": "21.7644%", "marginLeft": "-17%", "width": "34%"} }>
          <p className='g-pstyle1'>You've convinced us, now we see</p>
          <p className='g-pstyle1'>We'll never use those PEDs!</p>
        </div>
        <div id='g-ai3-27' className='g-Layer_1 g-aiAbs' style={ { "top": "93.4692%", "left": "81.1304%", "marginLeft": "-13.3333%", "width": "26.6667%"} }>
          <p className='g-pstyle1'>Good luck at Abu Dhabi trials!</p>
          <p className='g-pstyle1'>Thank you, thank you, Lachlan Giles!</p>
        </div>
      </div>
    </div>
  </div>
);

export default XSMobile;
/* End ai2jsx - 2020-12-15 14:19 */
