
/* Generated by ai2jsx v0.89.0 - 2020-12-15 14:19 */
/* ai file: Panel1.ai */

import React from 'react';
import { styles } from './styles.scss';
import panel from './Panel1-Mobile.jpg';

const Mobile = () => (
  <div className={`Mobile ${styles}`}>
    <div id='g-Mobile-box'>
      <div id='g-Panel1-Mobile' className='g-artboard' style={ { "width": "450px", "height": "3356px"} } data-aspect-ratio='0.134' data-min-width='450' data-max-width='599'>
        <img id='g-Panel1-Mobile-img' className='g-aiImg g-aiAbs' alt='' src={panel} />
        <div id='g-ai1-1' className='g-Layer_1 g-aiAbs' style={ { "top": "0.447%", "left": "4.1095%", "width": "43.3333%"} }>
          <p>Lachlan, with the PEDs</p>
          <p>Tell, us, do you use them, please?</p>
        </div>
        <div id='g-ai1-2' className='g-Layer_1 g-aiAbs' style={ { "top": "5.9297%", "left": "54.2248%", "width": "43.3333%"} }>
          <p>I would not snort them up my nose</p>
          <p>I would not drink them with a hose</p>
        </div>
        <div id='g-ai1-3' className='g-Layer_1 g-aiAbs' style={ { "top": "8.5221%", "left": "5.0518%", "width": "57.1111%"} }>
          <p>I won't inject them in my ass</p>
          <p>I'll never, ever take the gas</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-4' className='g-Layer_1 g-aiAbs' style={ { "top": "16.4779%", "left": "3.4527%", "width": "43.1111%"} }>
          <p>Would you use them in the gi?</p>
          <p>Would you at ADCC?</p>
        </div>
        <div id='g-ai1-5' className='g-Layer_1 g-aiAbs' style={ { "top": "22.2884%", "left": "53.6932%", "width": "43.1111%"} }>
          <p className='g-pstyle0'>I would not, could not, in the gi</p>
          <p className='g-pstyle0'>I would not at ADCC</p>
        </div>
        <div id='g-ai1-6' className='g-Layer_1 g-aiAbs' style={ { "top": "24.4636%", "left": "3.9359%", "width": "24%"} }>
          <p>I would not ever take the juice</p>
        </div>
        <div id='g-ai1-7' className='g-Layer_1 g-aiAbs' style={ { "top": "24.7616%", "left": "70.1865%", "width": "22.6667%"} }>
          <p>I do not use those PEDs</p>
        </div>
        <div id='g-ai1-8' className='g-Layer_1 g-aiAbs' style={ { "top": "26.1025%", "left": "4.0993%", "width": "19.5556%"} }>
          <p>I would not in the absolutes</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai1-9' className='g-Layer_1 g-aiAbs' style={ { "top": "26.2515%", "left": "79.9249%", "width": "17.5556%"} }>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-10' className='g-Layer_1 g-aiAbs' style={ { "top": "32.9857%", "left": "4.6788%", "width": "40.8889%"} }>
          <p>Lachlan, sorry for the spam</p>
          <p>But check out Gordon's Instagram!</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai1-11' className='g-Layer_1 g-aiAbs' style={ { "top": "38.4088%", "left": "53.7164%", "width": "42.6667%"} }>
          <p>Right now I'm fully at a loss</p>
          <p>Did he just say I'm on the sauce?</p>
        </div>
        <div id='g-ai1-12' className='g-Layer_1 g-aiAbs' style={ { "top": "40.9714%", "left": "4.603%", "width": "56.6667%"} }>
          <p>Why did he post that? Is he high?</p>
          <p>I can't believe this fucking guy</p>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
          <p>I would not ever take the juice</p>
          <p>I would not in the absolutes</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-13' className='g-Layer_1 g-aiAbs' style={ { "top": "50.0298%", "left": "6.1586%", "width": "60.2222%"} }>
          <p>Did you use in your last fight?</p>
          <p>Tell us, please, was Gordon right?</p>
        </div>
        <div id='g-ai1-14' className='g-Layer_1 g-aiAbs' style={ { "top": "51.4005%", "left": "26.7785%", "width": "56.4444%"} }>
          <p>I did not use in my last fight</p>
          <p>I tell you Gordon was not right</p>
          <p>I am natty, don't you see?</p>
          <p>The scientists can test my pee</p>
        </div>
        <div id='g-ai1-15' className='g-Layer_1 g-aiAbs' style={ { "top": "54.2014%", "left": "39.5556%", "width": "56.6667%"} }>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
        </div>
        <div id='g-ai1-16' className='g-Layer_1 g-aiAbs' style={ { "top": "55.7509%", "left": "60.3804%", "width": "33.3333%"} }>
          <p>I would not ever take the juice</p>
          <p>I would not in the </p>
          <p>absolutes</p>
        </div>
        <div id='g-ai1-17' className='g-Layer_1 g-aiAbs' style={ { "top": "58.1645%", "left": "60.6874%", "width": "36.6667%"} }>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-18' className='g-Layer_1 g-aiAbs' style={ { "top": "60.8462%", "left": "49.21%", "marginLeft": "-28.2222%", "width": "56.4444%"} }>
          <p className='g-pstyle1'>Lachlan, Lachlan, don't be cross</p>
          <p className='g-pstyle1'>But everyone is on the sauce.</p>
        </div>
        <div id='g-ai1-19' className='g-Layer_1 g-aiAbs' style={ { "top": "65.6436%", "left": "4.6333%", "width": "72.8889%"} }>
          <p>I've competed with the best</p>
          <p>And trust me, some would pass a test</p>
          <p>I don't want this to be a sport</p>
          <p>Where clean guys always come up short</p>
          <p>So let's not tell those who compete</p>
          <p>That those who win must always cheat</p>
        </div>
        <div id='g-ai1-20' className='g-Layer_1 g-aiAbs' style={ { "top": "72.9738%", "left": "27.6973%", "width": "71.1111%"} }>
          <p>We should not use those PEDs</p>
          <p>We should not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-21' className='g-Layer_1 g-aiAbs' style={ { "top": "74.5232%", "left": "4.6405%", "width": "41.3333%"} }>
          <p>Lachlan, please now, don't be mad</p>
          <p>But tell us, are those drugs so bad?</p>
        </div>
        <div id='g-ai1-22' className='g-Layer_1 g-aiAbs' style={ { "top": "80.3337%", "left": "53.9529%", "width": "42.6667%"} }>
          <p>The side effects I cannot list</p>
          <p>I'm no endocrinologist</p>
        </div>
        <div id='g-ai1-23' className='g-Layer_1 g-aiAbs' style={ { "top": "82.3302%", "left": "4.9777%", "width": "82.6667%"} }>
          <p>But we all know they're bad for you</p>
          <p>I will not die at fifty-two</p>
          <p>I would not, could not, take the gas</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai1-24' className='g-Layer_1 g-aiAbs' style={ { "top": "84.118%", "left": "41.5556%", "width": "56%"} }>
          <p>I do not need that muscle mass</p>
          <p>They may be big while I am small</p>
          <p>But I don't need turinabol</p>
        </div>
        <div id='g-ai1-25' className='g-Layer_1 g-aiAbs' style={ { "top": "90.1073%", "left": "4.4197%", "width": "69.1111%"} }>
          <p>Regardless of their body frame</p>
          <p>I'll tear their ACLs the same</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-26' className='g-Layer_1 g-aiAbs' style={ { "top": "92.5209%", "left": "20.6941%", "marginLeft": "-17.5556%", "width": "35.1111%"} }>
          <p className='g-pstyle1'>You've convinced us, now we see</p>
          <p className='g-pstyle1'>We'll never use those PEDs!</p>
        </div>
        <div id='g-ai1-27' className='g-Layer_1 g-aiAbs' style={ { "top": "92.5507%", "left": "81.7715%", "marginLeft": "-13.7778%", "width": "27.5556%"} }>
          <p className='g-pstyle1'>Good luck at Abu Dhabi trials!</p>
          <p className='g-pstyle1'>Thank you, thank you, Lachlan Giles!</p>
        </div>
      </div>
    </div>
  </div>
);

export default Mobile;
/* End ai2jsx - 2020-12-15 14:19 */
