
/* Generated by ai2jsx v0.89.0 - 2020-12-15 11:42 */
/* ai file: Panel1.ai */

import React from 'react';
import { styles } from './styles.scss';

const Artboard_6 = () => (
  <div className={`Artboard_6 ${styles}`}>
    <div id='g-Artboard_6-box'>
      <div id='g-Panel1-Artboard_6' className='g-artboard' style={ { "width": "450px", "height": "6488px"} } data-aspect-ratio='0.069' data-min-width='450' data-max-width='799'>
        <img id='g-Panel1-Artboard_6-img' className='g-aiImg g-aiAbs' alt='' src='./Panel1-Artboard_6.jpg' />
        <div id='g-ai1-1' className='g-Layer_1 g-aiAbs' style={ { "top": "0.2158%", "left": "4.1095%", "width": "43.3333%"} }>
          <p>Lachlan, with the PEDs</p>
          <p>Tell, us, do you use them, please?</p>
        </div>
        <div id='g-ai1-2' className='g-Layer_1 g-aiAbs' style={ { "top": "3.0826%", "left": "54.2248%", "width": "43.3333%"} }>
          <p>I would not snort them up my nose</p>
          <p>I would not drink them with a hose</p>
        </div>
        <div id='g-ai1-3' className='g-Layer_1 g-aiAbs' style={ { "top": "4.3927%", "left": "5.0518%", "width": "57.1111%"} }>
          <p>I won't inject them in my ass</p>
          <p>I'll never, ever take the gas</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-4' className='g-Layer_1 g-aiAbs' style={ { "top": "8.4926%", "left": "3.2305%", "width": "43.1111%"} }>
          <p>Would you use them in the gi?</p>
          <p>Would you at ADCC?</p>
        </div>
        <div id='g-ai1-5' className='g-Layer_1 g-aiAbs' style={ { "top": "11.5136%", "left": "53.6932%", "width": "43.1111%"} }>
          <p className='g-pstyle0'>I would not, could not, in the gi</p>
          <p className='g-pstyle0'>I would not at ADCC</p>
        </div>
        <div id='g-ai1-6' className='g-Layer_1 g-aiAbs' style={ { "top": "12.6079%", "left": "6.1581%", "width": "20%"} }>
          <p>I would not ever take the juice</p>
        </div>
        <div id='g-ai1-7' className='g-Layer_1 g-aiAbs' style={ { "top": "NaN%", "left": "29.7778%", "width": "45.1111%"} }>
          <p>&nbsp;</p>
          <p className='g-pstyle1'>I would not in the absolutes</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai1-8' className='g-Layer_1 g-aiAbs' style={ { "top": "12.9007%", "left": "71.7421%", "width": "28.4444%"} }>
          <p>I do not use those PEDs</p>
        </div>
        <div id='g-ai1-9' className='g-Layer_1 g-aiAbs' style={ { "top": "13.7022%", "left": "77.036%", "width": "20.8889%"} }>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-10' className='g-Layer_1 g-aiAbs' style={ { "top": "17.0469%", "left": "4.6788%", "width": "39.3333%"} }>
          <p>Lachlan, sorry for the spam</p>
          <p>But check out Gordon's Instagram!</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai1-11' className='g-Layer_1 g-aiAbs' style={ { "top": "19.852%", "left": "53.7164%", "width": "42.6667%"} }>
          <p>Right now I'm fully at a loss</p>
          <p>Did he just say I'm on the sauce?</p>
        </div>
        <div id='g-ai1-12' className='g-Layer_1 g-aiAbs' style={ { "top": "21.1776%", "left": "5.2696%", "width": "50.6667%"} }>
          <p>Why did he post that? Is he high?</p>
          <p>I can't believe this fucking guy</p>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
          <p>I would not ever take the juice</p>
          <p>I would not in the absolutes</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-13' className='g-Layer_1 g-aiAbs' style={ { "top": "25.5549%", "left": "6.1586%", "width": "56.4444%"} }>
          <p>Did you use in your last fight?</p>
          <p>Tell us, please, was Gordon right?</p>
        </div>
        <div id='g-ai1-14' className='g-Layer_1 g-aiAbs' style={ { "top": "26.3255%", "left": "27.2909%", "width": "51.3333%"} }>
          <p>I did not use in my last fight</p>
          <p>I tell you Gordon was not right</p>
          <p>I am natty, don't you see?</p>
          <p>The scientists can test my pee</p>
        </div>
        <div id='g-ai1-15' className='g-Layer_1 g-aiAbs' style={ { "top": "NaN%", "left": "41.5269%", "width": "62%"} }>
          <p>&nbsp;</p>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
        </div>
        <div id='g-ai1-16' className='g-Layer_1 g-aiAbs' style={ { "top": "NaN%", "left": "59.4915%", "width": "33.3333%"} }>
          <p>&nbsp;</p>
          <p>I would not ever take the juice</p>
          <p>I would not in the </p>
          <p>absolutes</p>
        </div>
        <div id='g-ai1-17' className='g-Layer_1 g-aiAbs' style={ { "top": "29.6085%", "left": "59.5762%", "width": "36.6667%"} }>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-18' className='g-Layer_1 g-aiAbs' style={ { "top": "30.8724%", "left": "49.21%", "marginLeft": "-28.2222%", "width": "56.4444%"} }>
          <p className='g-pstyle2'>Lachlan, Lachlan, don't be cross</p>
          <p className='g-pstyle2'>But everyone is on the sauce.</p>
        </div>
        <div id='g-ai1-19' className='g-Layer_1 g-aiAbs' style={ { "top": "33.2768%", "left": "4.6333%", "width": "72.8889%"} }>
          <p>I've competed with the best</p>
          <p>And trust me, some would pass a test</p>
          <p>I don't want this to be a sport</p>
          <p>Where clean guys always come up short</p>
          <p>So let's not tell those who compete</p>
          <p>That those who win must always cheat</p>
        </div>
        <div id='g-ai1-20' className='g-Layer_1 g-aiAbs' style={ { "top": "36.9605%", "left": "31.6973%", "width": "65.3333%"} }>
          <p>We should not use those PEDs</p>
          <p>We should not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-21' className='g-Layer_1 g-aiAbs' style={ { "top": "37.7928%", "left": "4.6405%", "width": "41.3333%"} }>
          <p className='g-pstyle3'>Lachlan, please now, don't be mad</p>
          <p className='g-pstyle3'>But tell us, are those drugs so bad?</p>
        </div>
        <div id='g-ai1-22' className='g-Layer_1 g-aiAbs' style={ { "top": "40.6443%", "left": "53.9529%", "width": "42.6667%"} }>
          <p className='g-pstyle3'>The side effects I cannot list</p>
          <p className='g-pstyle3'>I'm no endocrinologist</p>
        </div>
        <div id='g-ai1-23' className='g-Layer_1 g-aiAbs' style={ { "top": "41.8465%", "left": "4.9777%", "width": "58.8889%"} }>
          <p className='g-pstyle3'>But we all know they're bad for you</p>
          <p className='g-pstyle3'>I will not die at fifty-two</p>
          <p className='g-pstyle3'>I would not, could not, take the gas</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai1-24' className='g-Layer_1 g-aiAbs' style={ { "top": "42.7559%", "left": "43.8794%", "width": "53.3333%"} }>
          <p className='g-pstyle3'>I do not need that muscle mass</p>
          <p className='g-pstyle3'>They may be big while I am small</p>
          <p className='g-pstyle3'>But I don't need turinabol</p>
        </div>
        <div id='g-ai1-25' className='g-Layer_1 g-aiAbs' style={ { "top": "45.7768%", "left": "4.4197%", "width": "55.5556%"} }>
          <p className='g-pstyle3'>Regardless of their body frame</p>
          <p className='g-pstyle3'>I'll tear their ACLs the same</p>
          <p className='g-pstyle3'>I do not use those PEDs</p>
          <p className='g-pstyle3'>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai1-26' className='g-Layer_1 g-aiAbs' style={ { "top": "47.1178%", "left": "81.7715%", "marginLeft": "-13.7778%", "width": "27.5556%"} }>
          <p className='g-pstyle4'>Good luck at Abu Dhabi trials!</p>
          <p className='g-pstyle4'>Thank you, thank you, Lachlan Giles!</p>
        </div>
        <div id='g-ai1-27' className='g-Layer_1 g-aiAbs' style={ { "top": "47.1332%", "left": "18.1385%", "marginLeft": "-13.6667%", "width": "27.3333%"} }>
          <p className='g-pstyle4'>You've convinced us, now we see</p>
          <p className='g-pstyle4'>We'll never use those PEDs!</p>
        </div>
      </div>
    </div>
  </div>
);

export default Artboard_6;
/* End ai2jsx - 2020-12-15 11:42 */
