
/* Generated by ai2jsx v0.89.0 - 2020-12-15 13:51 */
/* ai file: Panel1.ai */

import React from 'react';
import { styles } from './styles.scss';
import panel from './Panel1-Ipad.jpg';

const Ipad = () => (
  <div className={`Ipad ${styles}`}>
    <div id='g-Ipad-box'>
      <div id='g-Panel1-Ipad' className='g-artboard' style={ { "width": "600px", "height": "4295.18407251883px"} } data-aspect-ratio='0.14' data-min-width='600' data-max-width='799'>
        <img id='g-Panel1-Ipad-img' className='g-aiImg g-aiAbs' alt='' src={panel} />
        <div id='g-ai2-1' className='g-Layer_1 g-aiAbs' style={ { "top": "0.7217%", "left": "5.5935%", "width": "42%"} }>
          <p>Lachlan, with the PEDs</p>
          <p>Tell, us, do you use them, please?</p>
        </div>
        <div id='g-ai2-2' className='g-Layer_1 g-aiAbs' style={ { "top": "6.2861%", "left": "54.1298%", "width": "42%"} }>
          <p>I would not snort them up my nose</p>
          <p>I would not drink them with a hose</p>
        </div>
        <div id='g-ai2-3' className='g-Layer_1 g-aiAbs' style={ { "top": "8.8937%", "left": "6.5062%", "width": "55.3333%"} }>
          <p>I won't inject them in my ass</p>
          <p>I'll never, ever take the gas</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai2-4' className='g-Layer_1 g-aiAbs' style={ { "top": "16.9259%", "left": "4.9574%", "width": "41.8333%"} }>
          <p>Would you use them in the gi?</p>
          <p>Would you at ADCC?</p>
        </div>
        <div id='g-ai2-5' className='g-Layer_1 g-aiAbs' style={ { "top": "22.7697%", "left": "53.615%", "width": "41.8333%"} }>
          <p className='g-pstyle0'>I would not, could not, in the gi</p>
          <p className='g-pstyle0'>I would not at ADCC</p>
        </div>
        <div id='g-ai2-6' className='g-Layer_1 g-aiAbs' style={ { "top": "24.9815%", "left": "5.4254%", "width": "23.3333%"} }>
          <p>I would not ever take the juice</p>
        </div>
        <div id='g-ai2-7' className='g-Layer_1 g-aiAbs' style={ { "top": "25.2841%", "left": "69.5887%", "width": "22%"} }>
          <p>I do not use those PEDs</p>
        </div>
        <div id='g-ai2-8' className='g-Layer_1 g-aiAbs' style={ { "top": "26.6112%", "left": "5.5836%", "width": "18.8333%"} }>
          <p>I would not in the absolutes</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai2-9' className='g-Layer_1 g-aiAbs' style={ { "top": "26.7975%", "left": "79.0202%", "width": "17%"} }>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai2-10' className='g-Layer_1 g-aiAbs' style={ { "top": "33.5492%", "left": "6.1449%", "width": "39.6667%"} }>
          <p>Lachlan, sorry for the spam</p>
          <p>But check out Gordon's Instagram!</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai2-11' className='g-Layer_1 g-aiAbs' style={ { "top": "39.0437%", "left": "53.6375%", "width": "41.3333%"} }>
          <p>Right now I'm fully at a loss</p>
          <p>Did he just say I'm on the sauce?</p>
        </div>
        <div id='g-ai2-12' className='g-Layer_1 g-aiAbs' style={ { "top": "41.628%", "left": "6.0714%", "width": "55%"} }>
          <p>Why did he post that? Is he high?</p>
          <p>I can't believe this fucking guy</p>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
          <p>I would not ever take the juice</p>
          <p>I would not in the absolutes</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai2-13' className='g-Layer_1 g-aiAbs' style={ { "top": "50.7778%", "left": "7.578%", "width": "58.3333%"} }>
          <p>Did you use in your last fight?</p>
          <p>Tell us, please, was Gordon right?</p>
        </div>
        <div id='g-ai2-14' className='g-Layer_1 g-aiAbs' style={ { "top": "52.1514%", "left": "27.5483%", "width": "54.6667%"} }>
          <p>I did not use in my last fight</p>
          <p>I tell you Gordon was not right</p>
          <p>I am natty, don't you see?</p>
          <p>The scientists can test my pee</p>
        </div>
        <div id='g-ai2-15' className='g-Layer_1 g-aiAbs' style={ { "top": "54.9685%", "left": "39.9228%", "width": "54.8333%"} }>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
        </div>
        <div id='g-ai2-16' className='g-Layer_1 g-aiAbs' style={ { "top": "56.5284%", "left": "60.0915%", "width": "32.3333%"} }>
          <p>I would not ever take the juice</p>
          <p>I would not in the </p>
          <p>absolutes</p>
        </div>
        <div id='g-ai2-17' className='g-Layer_1 g-aiAbs' style={ { "top": "58.973%", "left": "60.3888%", "width": "35.5%"} }>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai2-18' className='g-Layer_1 g-aiAbs' style={ { "top": "61.6737%", "left": "49.2734%", "marginLeft": "-27.3333%", "width": "54.6667%"} }>
          <p className='g-pstyle1'>Lachlan, Lachlan, don't be cross</p>
          <p className='g-pstyle1'>But everyone is on the sauce.</p>
        </div>
        <div id='g-ai2-19' className='g-Layer_1 g-aiAbs' style={ { "top": "66.5164%", "left": "6.1008%", "width": "70.6667%"} }>
          <p>I've competed with the best</p>
          <p>And trust me, some would pass a test</p>
          <p>I don't want this to be a sport</p>
          <p>Where clean guys always come up short</p>
          <p>So let's not tell those who compete</p>
          <p>That those who win must always cheat</p>
        </div>
        <div id='g-ai2-20' className='g-Layer_1 g-aiAbs' style={ { "top": "73.8967%", "left": "28.4381%", "width": "69%"} }>
          <p>We should not use those PEDs</p>
          <p>We should not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai2-21' className='g-Layer_1 g-aiAbs' style={ { "top": "75.4566%", "left": "6.1077%", "width": "40%"} }>
          <p>Lachlan, please now, don't be mad</p>
          <p>But tell us, are those drugs so bad?</p>
        </div>
        <div id='g-ai2-22' className='g-Layer_1 g-aiAbs' style={ { "top": "81.3469%", "left": "53.8665%", "width": "41.3333%"} }>
          <p>The side effects I cannot list</p>
          <p>I'm no endocrinologist</p>
        </div>
        <div id='g-ai2-23' className='g-Layer_1 g-aiAbs' style={ { "top": "83.3724%", "left": "6.4344%", "width": "80%"} }>
          <p>But we all know they're bad for you</p>
          <p>I will not die at fifty-two</p>
          <p>I would not, could not, take the gas</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai2-24' className='g-Layer_1 g-aiAbs' style={ { "top": "85.1652%", "left": "41.8598%", "width": "54.1667%"} }>
          <p>I do not need that muscle mass</p>
          <p>They may be big while I am small</p>
          <p>But I don't need turinabol</p>
        </div>
        <div id='g-ai2-25' className='g-Layer_1 g-aiAbs' style={ { "top": "91.1952%", "left": "5.894%", "width": "67%"} }>
          <p>Regardless of their body frame</p>
          <p>I'll tear their ACLs the same</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai2-26' className='g-Layer_1 g-aiAbs' style={ { "top": "93.663%", "left": "21.6531%", "marginLeft": "-17%", "width": "34%"} }>
          <p className='g-pstyle1'>You've convinced us, now we see</p>
          <p className='g-pstyle1'>We'll never use those PEDs!</p>
        </div>
        <div id='g-ai2-27' className='g-Layer_1 g-aiAbs' style={ { "top": "93.663%", "left": "80.7983%", "marginLeft": "-13.3333%", "width": "26.6667%"} }>
          <p className='g-pstyle1'>Good luck at Abu Dhabi trials!</p>
          <p className='g-pstyle1'>Thank you, thank you, Lachlan Giles!</p>
        </div>
      </div>
    </div>
  </div>
);

export default Ipad;
/* End ai2jsx - 2020-12-15 13:51 */
