
/* Generated by ai2jsx v0.89.0 - 2020-12-14 23:25 */
/* ai file: artisan-file.ai */

import React from 'react';
import './styles.scss';

const Artboard_1 = () => (
  <div className='Artboard_1'>
    <div id='g-Artboard_1-box'>
      <div id='g-artisan-file-Artboard_1' className='g-artboard' style={ { "width": "1000px", "height": "4000px"} } data-aspect-ratio='0.25' data-min-width='1200'>
        <img id='g-artisan-file-Artboard_1-img'
        className='g-aiImg g-aiAbs'
        alt='comic panel'
        src={require('./../Artboard_1/panels.jpg')}
        />
        <div id='g-ai0-1' className='g-Layer_1 g-aiAbs' style={ { "top": "1.0833%", "left": "5.2181%", "width": "42.0833%"} }>
          <p>Lachlan, with the PEDs</p>
          <p>Tell, us, do you use them, please?</p>
        </div>
        <div id='g-ai0-2' className='g-Layer_1 g-aiAbs' style={ { "top": "11.5833%", "left": "53.9681%", "width": "42.0833%"} }>
          <p>I would not snort them up my nose</p>
          <p>I would not drink them with a hose</p>
        </div>
        <div id='g-ai0-3' className='g-Layer_1 g-aiAbs' style={ { "top": "16.5625%", "left": "6.1348%", "width": "55.5%"} }>
          <p>I won't inject them in my ass</p>
          <p>I'll never, ever take the gas</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai0-4' className='g-Layer_1 g-aiAbs' style={ { "top": "31.5625%", "left": "4.7181%", "width": "42.0833%"} }>
          <p>Would you use them in the gi?</p>
          <p>Would you at ADCC?</p>
        </div>
        <div id='g-ai0-5' className='g-Layer_1 g-aiAbs' style={ { "top": "42.6042%", "left": "53.9681%", "width": "42.0833%"} }>
          <p className='g-pstyle0'>I would not, could not, in the gi</p>
          <p className='g-pstyle0'>I would not at ADCC</p>
        </div>
        <div id='g-ai0-6' className='g-Layer_1 g-aiAbs' style={ { "top": "46.6875%", "left": "7.5833%", "width": "19.5%"} }>
          <p>I would not ever take the juice</p>
        </div>
        <div id='g-ai0-7' className='g-Layer_1 g-aiAbs' style={ { "top": "47.6875%", "left": "71.5833%", "width": "27.8333%"} }>
          <p>I do not use those PEDs</p>
        </div>
        <div id='g-ai0-8' className='g-Layer_1 g-aiAbs' style={ { "top": "NaN%", "left": "4.9167%", "width": "18.5%"} }>
          <p>&nbsp;</p>
          <p>I would not in the absolutes</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai0-9' className='g-Layer_1 g-aiAbs' style={ { "top": "50.6458%", "left": "76.75%", "width": "20.3333%"} }>
          <p>I do not use them, Matt and Steve.</p>
        </div>
      </div>
    </div>
  </div>
);

export default Artboard_1;
/* End ai2jsx - 2020-12-14 23:25 */
