
/* Generated by ai2jsx v0.89.0 - 2020-12-15 14:19 */
/* ai file: Panel1.ai */

import React from 'react';
import { styles } from './styles.scss';
import panel from './Panel1-SMobile.jpg';

const SMobile = () => (
  <div className={`SMobile ${styles}`}>
    <div id='g-SMobile-box'>
      <div id='g-Panel1-SMobile' className='g-artboard' style={ { "width": "400px", "height": "2898px"} } data-aspect-ratio='0.138' data-min-width='400' data-max-width='449'>
        <img id='g-Panel1-SMobile-img' className='g-aiImg g-aiAbs' alt='' src={panel} />
        <div id='g-ai4-1' className='g-Layer_1 g-aiAbs' style={ { "top": "0.5521%", "left": "5.3901%", "width": "42.25%"} }>
          <p>Lachlan, with the PEDs</p>
          <p>Tell, us, do you use them, please?</p>
        </div>
        <div id='g-ai4-2' className='g-Layer_1 g-aiAbs' style={ { "top": "6.0732%", "left": "54.188%", "width": "42.25%"} }>
          <p>I would not snort them up my nose</p>
          <p>I would not drink them with a hose</p>
        </div>
        <div id='g-ai4-3' className='g-Layer_1 g-aiAbs' style={ { "top": "8.6611%", "left": "6.3076%", "width": "55.5%"} }>
          <p>I won't inject them in my ass</p>
          <p>I'll never, ever take the gas</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai4-4' className='g-Layer_1 g-aiAbs' style={ { "top": "16.6322%", "left": "4.7505%", "width": "42%"} }>
          <p>Would you use them in the gi?</p>
          <p>Would you at ADCC?</p>
        </div>
        <div id='g-ai4-5' className='g-Layer_1 g-aiAbs' style={ { "top": "22.4638%", "left": "53.6704%", "width": "42%"} }>
          <p className='g-pstyle0'>I would not, could not, in the gi</p>
          <p className='g-pstyle0'>I would not at ADCC</p>
        </div>
        <div id='g-ai4-6' className='g-Layer_1 g-aiAbs' style={ { "top": "24.6377%", "left": "5.221%", "width": "23.5%"} }>
          <p>I would not ever take the juice</p>
        </div>
        <div id='g-ai4-7' className='g-Layer_1 g-aiAbs' style={ { "top": "24.9482%", "left": "69.7302%", "width": "22%"} }>
          <p>I do not use those PEDs</p>
        </div>
        <div id='g-ai4-8' className='g-Layer_1 g-aiAbs' style={ { "top": "26.2595%", "left": "5.3801%", "width": "19%"} }>
          <p>I would not in the absolutes</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai4-9' className='g-Layer_1 g-aiAbs' style={ { "top": "26.432%", "left": "79.2125%", "width": "17.25%"} }>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai4-10' className='g-Layer_1 g-aiAbs' style={ { "top": "33.1608%", "left": "5.9444%", "width": "39.75%"} }>
          <p>Lachlan, sorry for the spam</p>
          <p>But check out Gordon's Instagram!</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai4-11' className='g-Layer_1 g-aiAbs' style={ { "top": "38.6128%", "left": "53.693%", "width": "41.5%"} }>
          <p>Right now I'm fully at a loss</p>
          <p>Did he just say I'm on the sauce?</p>
        </div>
        <div id='g-ai4-12' className='g-Layer_1 g-aiAbs' style={ { "top": "41.2008%", "left": "5.8705%", "width": "55.25%"} }>
          <p>Why did he post that? Is he high?</p>
          <p>I can't believe this fucking guy</p>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
          <p>I would not ever take the juice</p>
          <p>I would not in the absolutes</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai4-13' className='g-Layer_1 g-aiAbs' style={ { "top": "50.2761%", "left": "7.3853%", "width": "58.75%"} }>
          <p>Did you use in your last fight?</p>
          <p>Tell us, please, was Gordon right?</p>
        </div>
        <div id='g-ai4-14' className='g-Layer_1 g-aiAbs' style={ { "top": "51.6218%", "left": "27.4632%", "width": "55%"} }>
          <p>I did not use in my last fight</p>
          <p>I tell you Gordon was not right</p>
          <p>I am natty, don't you see?</p>
          <p>The scientists can test my pee</p>
        </div>
        <div id='g-ai4-15' className='g-Layer_1 g-aiAbs' style={ { "top": "54.4168%", "left": "39.9044%", "width": "55.25%"} }>
          <p>I would not, could not, in the gi</p>
          <p>I would not at ADCC</p>
        </div>
        <div id='g-ai4-16' className='g-Layer_1 g-aiAbs' style={ { "top": "55.9696%", "left": "60.1818%", "width": "32.5%"} }>
          <p>I would not ever take the juice</p>
          <p>I would not in the </p>
          <p>absolutes</p>
        </div>
        <div id='g-ai4-17' className='g-Layer_1 g-aiAbs' style={ { "top": "58.4196%", "left": "60.4807%", "width": "35.75%"} }>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai4-18' className='g-Layer_1 g-aiAbs' style={ { "top": "61.1111%", "left": "49.3247%", "marginLeft": "-27.5%", "width": "55%"} }>
          <p className='g-pstyle1'>Lachlan, Lachlan, don't be cross</p>
          <p className='g-pstyle1'>But everyone is on the sauce.</p>
        </div>
        <div id='g-ai4-19' className='g-Layer_1 g-aiAbs' style={ { "top": "65.9075%", "left": "5.9001%", "width": "71%"} }>
          <p>I've competed with the best</p>
          <p>And trust me, some would pass a test</p>
          <p>I don't want this to be a sport</p>
          <p>Where clean guys always come up short</p>
          <p>So let's not tell those who compete</p>
          <p>That those who win must always cheat</p>
        </div>
        <div id='g-ai4-20' className='g-Layer_1 g-aiAbs' style={ { "top": "73.2574%", "left": "28.3578%", "width": "69.25%"} }>
          <p>We should not use those PEDs</p>
          <p>We should not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai4-21' className='g-Layer_1 g-aiAbs' style={ { "top": "74.8102%", "left": "5.9071%", "width": "40.25%"} }>
          <p>Lachlan, please now, don't be mad</p>
          <p>But tell us, are those drugs so bad?</p>
        </div>
        <div id='g-ai4-22' className='g-Layer_1 g-aiAbs' style={ { "top": "80.6418%", "left": "53.9233%", "width": "41.5%"} }>
          <p>The side effects I cannot list</p>
          <p>I'm no endocrinologist</p>
        </div>
        <div id='g-ai4-23' className='g-Layer_1 g-aiAbs' style={ { "top": "82.6432%", "left": "6.2355%", "width": "80.5%"} }>
          <p>But we all know they're bad for you</p>
          <p>I will not die at fifty-two</p>
          <p>I would not, could not, take the gas</p>
          <p>&nbsp;</p>
        </div>
        <div id='g-ai4-24' className='g-Layer_1 g-aiAbs' style={ { "top": "84.4375%", "left": "41.8518%", "width": "54.5%"} }>
          <p>I do not need that muscle mass</p>
          <p>They may be big while I am small</p>
          <p>But I don't need turinabol</p>
        </div>
        <div id='g-ai4-25' className='g-Layer_1 g-aiAbs' style={ { "top": "90.4417%", "left": "5.6922%", "width": "67.25%"} }>
          <p>Regardless of their body frame</p>
          <p>I'll tear their ACLs the same</p>
          <p>I do not use those PEDs</p>
          <p>I do not use them, Matt and Steve.</p>
        </div>
        <div id='g-ai4-26' className='g-Layer_1 g-aiAbs' style={ { "top": "92.8571%", "left": "21.5696%", "marginLeft": "-17.125%", "width": "34.25%"} }>
          <p className='g-pstyle1'>You've convinced us, now we see</p>
          <p className='g-pstyle1'>We'll never use those PEDs!</p>
        </div>
        <div id='g-ai4-27' className='g-Layer_1 g-aiAbs' style={ { "top": "92.8916%", "left": "80.97%", "marginLeft": "-13.375%", "width": "26.75%"} }>
          <p className='g-pstyle1'>Good luck at Abu Dhabi trials!</p>
          <p className='g-pstyle1'>Thank you, thank you, Lachlan Giles!</p>
        </div>
      </div>
    </div>
  </div>
);

export default SMobile;
/* End ai2jsx - 2020-12-15 14:19 */
